title: "Zo-Dns"
description: "Security Research | Threat Research, Malware Analysis, RE, DFIR"
baseurl: ""
url: "https://zo-dns.github.io"
github_username: "Zo-Dns"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
