title: "Zo-Dns"
description: "Sit Pls | Ty"
baseurl: ""
url: "https://zo-dns.github.io"
github_username: "Zo-Dns"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
